name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: pnci1029/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name pnci1029
          git config user.email pnci1029@gmail.com
          git add -A .
          git commit -m "generated"
          git push
